# -*- coding: utf-8 -*-
#
# MPAS-Model documentation build configuration file, created by
# sphinx-quickstart on Sat Mar 25 14:39:11 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.intersphinx',
              'sphinx.ext.mathjax',
              'sphinx.ext.viewcode',
              'sphinx.ext.napoleon',
              'myst_parser']

# MyST extensions required by the technical-description subtree:
#   dollarmath: $...$ inline and $$...$$ block math
#   amsmath:    \begin{equation}...\end{equation} and other AMS environments
myst_enable_extensions = [
    'dollarmath',
    'amsmath',
]

# Generate deterministic anchors for Markdown headings so intra-doc and
# cross-doc links such as ``03-building.md#33-compiling-mpas`` resolve.
myst_heading_anchors = 4

autosummary_generate = True

# Otherwise, the Return parameter list looks different from the Parameters list
napoleon_use_rtype = False
# Otherwise, the Attributes parameter list looks different from the Parameters
# list
napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'CheMPAS-A'
copyright = u'Copyright (c) 2013-2026,  Los Alamos National Security, LLC (LANS) (Ocean: LA-CC-13-047;' \
            u'Land Ice: LA-CC-13-117) and the University Corporation for Atmospheric Research (UCAR).'
author = u'CheMPAS-A contributors'

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|. CheMPAS-A uses calendar versioning (YY.MM),
# tracked independently from the MPAS-Model baseline (currently v8.4.1,
# commit 91c5eac) it derives from.
if 'DOCS_VERSION' in os.environ:
    version = os.environ.get('DOCS_VERSION')
    release = version
else:
    # The short YY.MM version.
    version = '26.08'
    # The full version, including the public MVP snapshot.
    release = '26.08 MVP (v2026.08.01-rc2)'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files. The root README is a
# maintainer build recipe and is intentionally not part of the public site.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'README.md', 'Thumbs.db', '.DS_Store',
                    'design_docs/template.md',
                    'superpowers/**']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_logo = '_static/logo_chempas_ncar_blue.svg'

# Custom CSS layered on top of sphinx_rtd_theme. See _static/custom.css for
# the sidebar-overflow fix that lets long nav trees scroll.
html_css_files = ['custom.css']

# Public source links in the Read the Docs theme point to the documentation
# mirror. The model source described by these pages is linked explicitly from
# the landing page at its immutable MVP tag.
html_context = {
    'display_github': True,
    'github_user': 'NCAR',
    'github_repo': 'CheMPAS-A-Docs',
    'github_version': 'main',
    'conf_py_path': '/docs/',
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'chempas_a_doc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'chempas_a.tex', u'CheMPAS-A Documentation',
     author, 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'chempas_a', u'CheMPAS-A Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'chempas_a', u'CheMPAS-A Documentation',
     author, 'CheMPAS-A', 'One line description of project.',
     'Miscellaneous'),
]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'xarray': ('https://docs.xarray.dev/en/stable/', None)}


github_doc_root = 'https://github.com/rtfd/recommonmark/tree/master/doc/'
